### ISSUE TITLE
Simplify content block CSS

### ISSUE THREAD

**Issue by GaryJones** [highrisedigital/better-admin-post-types#6]
The current CSS has:
```css
.bapt-content-wrapper .bapt-content-block {
	float: left;
	width: 31%;
	min-width: auto;
	margin: 0 1% 1% 0;
}

@media screen and (min-width: 721px) {
	.bapt-content-wrapper .bapt-content-block {
		min-height: 320px;
	}
}

@media screen and (max-width: 720px) {
	.bapt-content-wrapper .bapt-content-block {
		float: none;
		width: 100%;
	}
}
```

This could be simplified in a mobile-first CSS into something like (untested):

```css
.bapt-content-wrapper .bapt-content-block {
	margin: 0 1% 1% 0;
}

@media screen and (min-width: 721px) {
	.bapt-content-wrapper .bapt-content-block {
		float: left;
		width: 31%;
		min-height: 320px;
	}
}
```
